trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Docker
  jobs:
  - job: BuildDocker
    dependsOn: BuildAndTestCode
    steps:
    - task: Docker@2
      displayName: "Build and Push Container"
      inputs:
        containerRegistry: 'Quintin Demo Registry'
        repository: 'azure-vote-front'
        command: 'buildAndPush'
        Dockerfile: '$(System.DefaultWorkingDirectory)/azure-vote/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)/azure-vote/'
        tags: 'v1'
